name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Puedes elegir una versión específica

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci  # Instalación limpia de dependencias
      
      - run: npm run build  # Compila el proyecto
      
      

      # Paso adicional para despliegue en Firebase
      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'  # Solo despliega desde la rama 'main'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting
